apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-tracker
  namespace: task-tracker
  labels:
    app: task-tracker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: task-tracker
  template:
    metadata:
      labels:
        app: task-tracker
    spec:
      containers:
        - name: app
          image: blurrysignature/task-tracker-web:v1.0
          ports:
            - name: task-tracker
              containerPort: 8000
          env:
            - name: HOST
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: host
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: port
            - name: PG_DBNAME
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: database
            - name: PG_USER
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: user
            - name: PG_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: password
          startupProbe:
            httpGet:
              path: /
              port: 8000
            initialDelaySeconds: 10
            failureThreshold: 5
            periodSeconds: 3
            timeoutSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 10