apiVersion: v1
kind: Service
metadata:
  name: task-tracker
  namespace: task-tracker
  labels:
    app: task-tracker
spec:
  type: NodePort
  selector:
    app: task-tracker
  ports:
    - name: task-tracker
      protocol: TCP
      port: 8000
      nodePort: 30303
      targetPort: task-tracker