apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: task-tracker
data:
  host: postgres
  port: "5432"
  database: task_tracker

---

apiVersion: v1
kind: Secret
metadata:
  name: pg-secrets
  namespace: task-tracker
data:
  user: cG9zdGdyZXM=
  password: cG9zdGdyZXM=

---

apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: task-tracker
data:
  user: dGFza190cmFja2VyX3VzZXI=
  password: MTIz