apiVersion: v1
kind: PersistentVolume
metadata:
  name: pg-data-pv
  namespace: task-tracker
spec:
  capacity:
    storage: 1Gi
  storageClassName: standart
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /var/lib/docker/volumes/task_tracker_postgres_data/_data

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pg-data-pvc
  namespace: task-tracker
spec:
  volumeName: pg-data-pv
  storageClassName: standart
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi