apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: task-tracker
  labels:
    app: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      initContainers:
        - name: pg-init
          image: busybox
          command:
            - /bin/sh
            - -c
            - cp /docker-entrypoint-initdb.d/initdb.sh /shared/ && chmod 755 /shared/initdb.sh
          volumeMounts:
            - name: from-host
              mountPath: /docker-entrypoint-initdb.d
            - name: to-postgres
              mountPath: /shared
      containers:
        - name: postgres
          image: postgres:15-alpine
          ports:
            - name: postgres
              containerPort: 5432
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: pg-secrets
                  key: user
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pg-secrets
                  key: password
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: database
          startupProbe:
            exec:
              command: ["pg_isready", "-U", "postgres", "-d", "task_tracker"]
            initialDelaySeconds: 5
            failureThreshold: 3
            periodSeconds: 3
            timeoutSeconds: 10
          livenessProbe:
            exec:
              command: ["pg_isready", "-U", "postgres", "-d", "task_tracker"]
            failureThreshold: 2
            periodSeconds: 5
            timeoutSeconds: 10
          readinessProbe:
            exec:
              command: ["pg_isready", "-U", "postgres", "-d", "task_tracker"]
            failureThreshold: 2
            periodSeconds: 5
            timeoutSeconds: 10
          volumeMounts:
            - name: pg-data
              mountPath: /var/lib/postgresql/data
            - name: to-postgres
              mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: pg-data
          persistentVolumeClaim:
            claimName: pg-data-pvc
        - name: from-host
          hostPath:
            path: /home/pasha/Projects/task_tracker/initdb
        - name: to-postgres
          emptyDir: {}