apiVersion: v1
kind: Service
metadata:
  name: task-tracker
  namespace: {{ .Values.namespace }}
  labels:
    app: task-tracker
spec:
  type: NodePort
  selector:
    app: task-tracker
  ports:
    - name: task-tracker
      protocol: TCP
      port: {{ .Values.taskTracker.port }}
      nodePort: {{ .Values.nodePort }}
      targetPort: task-tracker