apiVersion: v1
kind: PersistentVolume
metadata:
  name: pg-data-pv
  namespace: {{ .Values.namespace }}
spec:
  capacity:
    storage: 1Gi
  storageClassName: {{ .Values.storageClassName }}
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: {{ .Values.persistentVolumePath }}

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pg-data-pvc
  namespace: {{ .Values.namespace }}
spec:
  volumeName: pg-data-pv
  storageClassName: {{ .Values.storageClassName }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi